config/routes.rb
Rails.application.routes.draw do
  resources :animes do
    collection do
      get :search
    end
  end
  resources :rankings, only: [:index, :new, :create, :edit, :update, :destroy]
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :goals
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :trainers, except: [:destroy]
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :sport, presence: true
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    if current_user.admin?
      @goals = Goal.paginate(page: params[:page], per_page: 5)
    else
      @goals = current_user.goals.paginate(page: params[:page], per_page: 5)
    end
  end

  def new
    @goal = Goal.new
  end

  def edit
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    if @goal.save
      flash[:notice] = "Goal was created successfully."
      redirect_to @goal
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @goal.update(goal_params)
      flash[:notice] = "Goal was updated successfully."
      redirect_to @goal
    else
      render 'edit'
    end
  end

  def destroy
    @goal.destroy
    redirect_to goals_path
  end

  private

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:name, :sport, )
  end

  def require_same_user
    if current_user != @goal.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own goal"
      redirect_to @goal
    end
  end

end

app/views/goals/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-7">
      <%= render 'shared/errors', obj: @goal %>
      <%= form_with(model: @goal, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row mb-3 align-items-center justify-content-center">
          <%= f.label :name, class: "col-1 col-form-label text-black mb-0 text-right" %>
          <div class="col-9">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter your goal name" %>
          </div>
        </div>

        <div class="form-group row mb-3 align-items-center justify-content-center">
          <%= f.label :sport, class: "col-1 col-form-label text-black mb-0 text-right" %>
          <div class="col-9">
            <%= f.text_field :sport, class: "form-control shadow rounded" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <div class="col-10 text-center">
            <%= f.submit 'Save', class: "btn btn-outline-secondary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-10 text-center">
      <%= link_to 'Cancel and return to Goals listing', goals_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/goals/_goal.html.erb
<div class="container">
  <% @goals.each do |goal| %>
    <% if logged_in? && (goal.user == current_user || current_user.admin?) %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              <% if goal.user %>
                by <%= link_to goal.user.username, user_path(goal.user) %>
              <% end %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to goal.name, goal_path(goal) %></h5>
              <p class="card-text"><%= goal.sport %></p>
              <div class="btn-group" role="group">
                <% if logged_in? && (goal.user == current_user || current_user.admin?) %>
                  <%= link_to "View", goal_path(goal), class: "btn btn-outline-primary" %>
                  <%= link_to "Edit", edit_goal_path(goal), class: "btn btn-outline-secondary" %>
                  <%= link_to "Delete", goal_path(goal), class: "btn btn-outline-danger", data: { turbo_method: :delete, confirm: "Are you sure?" } %>
                <% end %>
              </div>
            </div>
            <div class="card-footer text-muted">
              <small>
                Created <%= time_ago_in_words(goal.created_at) %> ago, edited <%= time_ago_in_words(goal.updated_at) %> ago
              </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/goals/edit.html.erb
<h1 class="text-center mt-4">Edit Goal</h1>
<%= render 'form' %>

app/views/goals/index.html.erb
<h1 class="text-center mt-4">All Goals</h1>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @goals %>
  </div>
  <%= will_paginate @goals, :container => false %>
</div>

<%= render 'goal' %>

<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%= page_entries_info @goals %>
  </div>
  <%= will_paginate @goals, :container => false %>
</div>

app/views/goals/new.html.erb
<h1 class="text-center mt-4">Create a New Goal</h1>
<%= render 'form' %>

app/views/goals/show.html.erb
<h2 class="text-center mt-4"><%= @goal.name %></h2>

<div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= @goal.user.username if @goal.user %>
            <%= link_to gravatar_for(@goal.user, size: 50), user_path(@goal.user) %>
          </div>
          <div class="card-body">
            <p class="card-text"><%= @goal.sport %></p>
            <% if logged_in? && (@goal.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_goal_path(@goal), class: "btn btn-secondary" %>
              <%= button_to "Delete", goal_path(@goal), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>
              Created <%= time_ago_in_words(@goal.created_at) %> ago,
              edited <%= time_ago_in_words(@goal.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
</div>

<p><%= link_to 'Create new goal', new_goal_path %></p>