config/routes.rb
Rails.application.routes.draw do
  resources :animes do
    collection do
      get :search
    end
  end
  resources :rankings, only: [:index, :new, :create, :edit, :update, :destroy]
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :goals
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :trainers, except: [:destroy]
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  validates :name, presence: true, length: { minimum: 1, maximum: 50 }
  validates_uniqueness_of :name
  has_many :user_trainers
  has_many :users, through: :user_trainers
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @trainer = Trainer.new
  end

  def index
    @trainers = Trainer.paginate(page: params[:page], per_page: 5)
  end

  def show
    @trainer = Trainer.find(params[:id])
    @users = @trainer.users.paginate(page: params[:page], per_page: 5)
  end

  def create
    @trainer = Trainer.new(trainer_params)
    if @trainer.save
      flash[:notice] = "Trainer was successfully created"
      redirect_to @trainer
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @trainer = Trainer.find(params[:id])
  end

  def update
    @trainer = Trainer.find(params[:id])
    if @trainer.update(trainer_params)
      flash[:notice] = "Trainer updated successfully"
      redirect_to @trainer
    else
      render 'edit'
    end
  end

  private

  def trainer_params
    params.require(:trainer).permit(:name)
  end

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:alert] = "Only admins can perform that action"
      redirect_to trainers_path
    end
  end

end

app/views/trainers/_clients.html.erb
<div class="container">
  <% @users.each do |user| %>
    <% if logged_in? && (user == current_user || current_user.admin?) %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
                <%= link_to user.username, user_path(user) %>
            </div>
            <div class="card-body">
              <div class="btn-group" role="group">
                <% if logged_in? && (user == current_user || current_user.admin?) %>
                  <%= link_to "View", user_path(user), class: "btn btn-outline-primary" %>
                  <%= link_to "Edit", edit_user_path(user), class: "btn btn-outline-secondary" %>
                <% end %>
              </div>
            </div>
            <div class="card-footer text-muted">
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/trainers/_form.html.erb
<%= render 'shared/errors', obj: @trainer %>
<%= form_with(model: @trainer, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
  <div class="form-group row mb-3 align-items-center justify-content-center">
    <%= f.label :name, "Trainer Name", class: "col-2 col-form-label text-black mb-0 text-right" %>
    <div class="col-8">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a Name" %>
    </div>
  </div>

  <div class="form-group row justify-content-center">
    <div class="col-10 text-center">
      <%= f.submit class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

app/views/trainers/_trainer.html.erb
<%= link_to trainer.name, trainer_path(trainer), class: "badge rounded-pill bg-info text-light mr-4" %>

app/views/trainers/edit.html.erb
<h1 class="text-center mt-4">Edit Trainer</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-10 text-center">
      <%= link_to 'Cancel and return to Trainers', trainers_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/trainers/index.html.erb
<h1 class="text-center mt-4">All Trainers</h1>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @trainers %>
  </div>
  <%= will_paginate @trainers, :container => false %>
</div>

<div class="container">
  <% @trainers.each do |trainer| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to trainer.name, trainer_path(trainer) %></h5>
            <p class="card-text"><%= pluralize(trainer.users.count, "client") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>
              Created <%= time_ago_in_words(trainer.created_at) %> ago,
              edited <%= time_ago_in_words(trainer.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @trainers %>
  </div>
  <%= will_paginate @trainers, :container => false %>
</div>

app/views/trainers/new.html.erb
<h1 class="text-center mt-4">Add a New Trainer</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @trainer %>
      <%= form_with(model: @trainer, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row mb-3 align-items-center justify-content-center">
          <%= f.label :name, "Trainer Name", class: "col-2 col-form-label text-black mb-0 text-right" %>
          <div class="col-8">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a Name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <div class="col-10 text-center">
            <%= f.submit class: "btn btn-outline-secondary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-10 text-center">
      <%= link_to 'Cancel and return to Goals listing', goals_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/trainers/show.html.erb
<h1 class="text-center mt-4">Trainer: <%= @trainer.name %>'s profile</h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit Trainer", edit_trainer_path(@trainer), class: "btn btn-outline-secondary" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Clients</h3>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @users %>
  </div>
  <%= will_paginate @users, :container => false %>
</div>

<%= render 'trainers/clients' %>

<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%= page_entries_info @users %>
  </div>
  <%= will_paginate @users, :container => false %>
</div>