config/routes.rb
Rails.application.routes.draw do
  resources :animes do
    collection do
      get :search
    end
  end
  resources :rankings, only: [:index, :new, :create, :edit, :update, :destroy]
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :goals
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :trainers, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer id='sticky-footer' class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; COAK App</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "ANIME APP", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Anime Compendium", animes_path, class: "nav-link" %>
        </li>

        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
            </a>
            <ul class="dropdown-menu">
              <%= link_to "View Your Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Vew Your Anime Rankings", rankings_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit Your Profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Delete Your Profile", user_path(current_user), class: "dropdown-item text-danger", data: { turbo_method: :delete, confirm: "Are you sure?" } %>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, class:"nav-link text-light", data: {turbo_method: :delete}%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
        </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_importmap_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>-->
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>